/**
 * CLI template registry.
 *
 * Each template generates a set of files for the target project.
 * Templates: static-html, vite-ts, mapspec
 */

export const TEMPLATES = ["static-html", "vite-ts", "mapspec"] as const;
export type TemplateName = typeof TEMPLATES[number];

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface TemplateContext {
  projectName: string;
  provider: string;
  cliVersion: string;
}

export interface Template {
  name: TemplateName;
  description: string;
  generate(ctx: TemplateContext): GeneratedFile[];
}

const staticHtmlTemplate: Template = {
  name: "static-html",
  description: "Standalone HTML file with inline GIS Engine CDN imports",
  generate(ctx) {
    return [
      {
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${ctx.projectName} — GIS Engine</title>
  <style>
    body { margin: 0; font-family: system-ui, sans-serif; }
    #map { width: 100vw; height: 100vh; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script type="module">
    import { createMap, applyCommands } from "https://unpkg.com/@gis-engine/engine";

    const spec = {
      version: "0.2",
      sources: {
        points: {
          type: "geojson",
          data: { type: "FeatureCollection", features: [] }
        }
      },
      layers: [
        { id: "points-layer", type: "circle", source: "points", paint: { "circle-radius": 6, "circle-color": "#3b82f6" } }
      ]
    };

    const container = document.getElementById("map");
    const map = await createMap(container, spec, { renderer: "maplibre" });
    console.log("[${ctx.projectName}] map created", map.exportSpec());
  </script>
</body>
</html>
`,
      },
      {
        path: "README.md",
        content: `# ${ctx.projectName}

Generated by \`create-gis-map\` v${ctx.cliVersion} using the **static-html** template.

## Usage

Open \`index.html\` in a browser.

## Provider

Current provider: \`${ctx.provider}\`
`,
      },
    ];
  },
};

const viteTsTemplate: Template = {
  name: "vite-ts",
  description: "Vite + TypeScript project with GIS Engine",
  generate(ctx) {
    return [
      {
        path: "package.json",
        content: JSON.stringify({
          name: ctx.projectName,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "vite",
            build: "tsc && vite build",
            preview: "vite preview",
          },
          dependencies: {
            "@gis-engine/engine": "^0.2.0",
            "@gis-engine/ai": "^0.2.0",
          },
          devDependencies: {
            typescript: "^5.7.0",
            vite: "^5.4.0",
          },
        }, null, 2) + "\n",
      },
      {
        path: "tsconfig.json",
        content: JSON.stringify({
          compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "bundler",
            strict: true,
            esModuleInterop: true,
            outDir: "./dist",
          },
          include: ["src"],
        }, null, 2) + "\n",
      },
      {
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${ctx.projectName}</title>
</head>
<body>
  <div id="map" style="width:100vw;height:100vh;"></div>
  <script type="module" src="/src/main.ts"></script>
</body>
</html>
`,
      },
      {
        path: "src/main.ts",
        content: `import { createMap } from "@gis-engine/engine";

const spec = {
  version: "0.2" as const,
  sources: {
    points: {
      type: "geojson" as const,
      data: { type: "FeatureCollection" as const, features: [] },
    },
  },
  layers: [
    {
      id: "points-layer",
      type: "circle" as const,
      source: "points",
      paint: { "circle-radius": 6, "circle-color": "#3b82f6" },
    },
  ],
};

const container = document.getElementById("map")!;
const map = await createMap(container, spec, { renderer: "maplibre" });
console.log("[${ctx.projectName}] map ready", map.exportSpec());
`,
      },
      {
        path: "README.md",
        content: `# ${ctx.projectName}

Generated by \`create-gis-map\` v${ctx.cliVersion} using the **vite-ts** template.

## Usage

\`\`\`bash
npm install
npm run dev
\`\`\`

## Provider

Current provider: \`${ctx.provider}\`
`,
      },
    ];
  },
};

const mapspecTemplate: Template = {
  name: "mapspec",
  description: "Minimal MapSpec JSON file only",
  generate(ctx) {
    return [
      {
        path: "map.json",
        content: JSON.stringify({
          version: "0.2",
          sources: {
            points: {
              type: "geojson",
              data: { type: "FeatureCollection", features: [] },
            },
          },
          layers: [
            {
              id: "points-layer",
              type: "circle",
              source: "points",
              paint: { "circle-radius": 6, "circle-color": "#3b82f6" },
            },
          ],
        }, null, 2) + "\n",
      },
      {
        path: "README.md",
        content: `# ${ctx.projectName}

Generated by \`create-gis-map\` v${ctx.cliVersion} using the **mapspec** template.

## Usage

Load \`map.json\` with any GIS Engine runtime:

\`\`\`js
import { createMap } from "@gis-engine/engine";
const spec = JSON.parse(await fetch("./map.json").then(r => r.text()));
const map = await createMap(container, spec, { renderer: "maplibre" });
\`\`\`

## Provider

Current provider: \`${ctx.provider}\`
`,
      },
    ];
  },
};

const registry: Record<TemplateName, Template> = {
  "static-html": staticHtmlTemplate,
  "vite-ts": viteTsTemplate,
  "mapspec": mapspecTemplate,
};

export function getTemplate(name: string): Template | undefined {
  return registry[name as TemplateName];
}
