/**
 * CLI template registry.
 *
 * Each template generates a set of files for the target project.
 * Templates: static-html, vite-ts, mapspec
 */

export const TEMPLATES = ["static-html", "vite-ts", "mapspec", "app"] as const;
export type TemplateName = typeof TEMPLATES[number];

export interface GeneratedFile {
  path: string;
  content: string;
}

export interface TemplateContext {
  projectName: string;
  provider: string;
  cliVersion: string;
}

export type AppType = "explorer" | "dashboard" | "locator";

export interface AppConfig {
  appType: AppType;
  title: string;
  description: string;
  components: string[];
}

export interface AppTemplateContext extends TemplateContext {
  appConfig?: AppConfig;
}

export interface AppConfigInput {
  appType?: AppType;
  title?: string;
  description?: string;
  components?: string[];
}

export const APP_COMPONENTS = [
  "LayerPanel",
  "FeaturePopup",
  "Legend",
  "SearchBox",
  "BasemapSwitcher",
] as const;

export type AppComponentName = typeof APP_COMPONENTS[number];

const DEFAULT_APP_COMPONENTS: Record<AppType, AppComponentName[]> = {
  explorer: ["LayerPanel", "Legend", "FeaturePopup", "SearchBox", "BasemapSwitcher"],
  dashboard: ["LayerPanel", "Legend", "FeaturePopup"],
  locator: ["SearchBox", "BasemapSwitcher", "FeaturePopup"],
};

const APP_COMPONENT_SET = new Set<string>(APP_COMPONENTS);

export function normalizeAppConfig(
  appConfig: AppConfigInput | undefined,
  defaults: { projectName: string; description: string },
): AppConfig {
  const appType = appConfig?.appType === "dashboard" || appConfig?.appType === "locator"
    ? appConfig.appType
    : "explorer";
  const title = typeof appConfig?.title === "string" && appConfig.title.trim().length > 0
    ? appConfig.title
    : defaults.projectName;
  const description = typeof appConfig?.description === "string" && appConfig.description.trim().length > 0
    ? appConfig.description
    : defaults.description;
  const filteredComponents = (Array.isArray(appConfig?.components) ? appConfig.components : [])
    .filter((component): component is AppComponentName =>
      typeof component === "string" && APP_COMPONENT_SET.has(component)
    )
    .filter((component, index, items) => items.indexOf(component) === index);

  return {
    appType,
    title,
    description,
    components: filteredComponents.length > 0 ? filteredComponents : DEFAULT_APP_COMPONENTS[appType],
  };
}

export interface Template {
  name: TemplateName;
  description: string;
  generate(ctx: TemplateContext): GeneratedFile[];
}

const staticHtmlTemplate: Template = {
  name: "static-html",
  description: "Standalone HTML file with inline GIS Engine CDN imports",
  generate(ctx) {
    return [
      {
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${ctx.projectName} — GIS Engine</title>
  <style>
    body { margin: 0; font-family: system-ui, sans-serif; }
    #map { width: 100vw; height: 100vh; }
  </style>
</head>
<body>
  <div id="map"></div>
  <script type="module">
    import { createMap, applyCommands } from "https://unpkg.com/@gis-engine/engine";

    const spec = {
      version: "0.2",
      sources: {
        points: {
          type: "geojson",
          data: { type: "FeatureCollection", features: [] }
        }
      },
      layers: [
        { id: "points-layer", type: "circle", source: "points", paint: { "circle-radius": 6, "circle-color": "#3b82f6" } }
      ]
    };

    const container = document.getElementById("map");
    const map = await createMap(container, spec, { renderer: "maplibre" });
    console.log("[${ctx.projectName}] map created", map.exportSpec());
  </script>
</body>
</html>
`,
      },
      {
        path: "README.md",
        content: `# ${ctx.projectName}

Generated by \`create-gis-map\` v${ctx.cliVersion} using the **static-html** template.

## Usage

Open \`index.html\` in a browser.

## Provider

Current provider: \`${ctx.provider}\`
`,
      },
    ];
  },
};

const viteTsTemplate: Template = {
  name: "vite-ts",
  description: "Vite + TypeScript project with GIS Engine",
  generate(ctx) {
    return [
      {
        path: "package.json",
        content: JSON.stringify({
          name: ctx.projectName,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "vite",
            build: "tsc && vite build",
            preview: "vite preview",
          },
          dependencies: {
            "@gis-engine/engine": "^0.2.0",
            "@gis-engine/ai": "^0.2.0",
          },
          devDependencies: {
            typescript: "^5.7.0",
            vite: "^5.4.0",
          },
        }, null, 2) + "\n",
      },
      {
        path: "tsconfig.json",
        content: JSON.stringify({
          compilerOptions: {
            target: "ES2022",
            module: "ESNext",
            moduleResolution: "bundler",
            strict: true,
            esModuleInterop: true,
            outDir: "./dist",
          },
          include: ["src"],
        }, null, 2) + "\n",
      },
      {
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${ctx.projectName}</title>
</head>
<body>
  <div id="map" style="width:100vw;height:100vh;"></div>
  <script type="module" src="/src/main.ts"></script>
</body>
</html>
`,
      },
      {
        path: "src/main.ts",
        content: `import { createMap } from "@gis-engine/engine";

const spec = {
  version: "0.2" as const,
  sources: {
    points: {
      type: "geojson" as const,
      data: { type: "FeatureCollection" as const, features: [] },
    },
  },
  layers: [
    {
      id: "points-layer",
      type: "circle" as const,
      source: "points",
      paint: { "circle-radius": 6, "circle-color": "#3b82f6" },
    },
  ],
};

const container = document.getElementById("map")!;
const map = await createMap(container, spec, { renderer: "maplibre" });
console.log("[${ctx.projectName}] map ready", map.exportSpec());
`,
      },
      {
        path: "README.md",
        content: `# ${ctx.projectName}

Generated by \`create-gis-map\` v${ctx.cliVersion} using the **vite-ts** template.

## Usage

\`\`\`bash
npm install
npm run dev
\`\`\`

## Provider

Current provider: \`${ctx.provider}\`
`,
      },
    ];
  },
};

const mapspecTemplate: Template = {
  name: "mapspec",
  description: "Minimal MapSpec JSON file only",
  generate(ctx) {
    return [
      {
        path: "map.json",
        content: JSON.stringify({
          version: "0.2",
          sources: {
            points: {
              type: "geojson",
              data: { type: "FeatureCollection", features: [] },
            },
          },
          layers: [
            {
              id: "points-layer",
              type: "circle",
              source: "points",
              paint: { "circle-radius": 6, "circle-color": "#3b82f6" },
            },
          ],
        }, null, 2) + "\n",
      },
      {
        path: "README.md",
        content: `# ${ctx.projectName}

Generated by \`create-gis-map\` v${ctx.cliVersion} using the **mapspec** template.

## Usage

Load \`map.json\` with any GIS Engine runtime:

\`\`\`js
import { createMap } from "@gis-engine/engine";
const spec = JSON.parse(await fetch("./map.json").then(r => r.text()));
const map = await createMap(container, spec, { renderer: "maplibre" });
\`\`\`

## Provider

Current provider: \`${ctx.provider}\`
`,
      },
    ];
  },
};

const appTemplate: Template = {
  name: "app",
  description: "Full interactive map application (Vite + React + Tailwind)",
  generate(ctx) {
    const appCtx = ctx as AppTemplateContext;
    const cfg: AppConfig = normalizeAppConfig(appCtx.appConfig, {
      projectName: ctx.projectName,
      description: `Interactive map generated by GIS Engine CLI v${ctx.cliVersion}`,
    });

    const hasComponent = (name: string) => cfg.components.includes(name);

    const componentImports = cfg.components
      .map((c) => `import ${c} from "./components/${c}";`)
      .join("\n");

    const componentRender = cfg.components
      .map((c) => `          <${c} map={map} spec={spec} />`)
      .join("\n");

    const componentFiles: GeneratedFile[] = [];

    if (hasComponent("LayerPanel")) {
      componentFiles.push({
        path: "src/components/LayerPanel.tsx",
        content: `import { useState } from "react";
import maplibregl from "maplibre-gl";

interface LayerInfo { id: string; type: string; visible: boolean; }

interface Props {
  map: maplibregl.Map | null;
  spec: Record<string, unknown>;
}

export default function LayerPanel({ map, spec }: Props) {
  const layers: LayerInfo[] = ((spec.layers as Array<Record<string, unknown>>) ?? []).map((l) => ({
    id: String(l.id ?? "unknown"),
    type: String(l.type ?? "fill"),
    visible: (l.layout as Record<string, unknown>)?.visibility !== "none",
  }));

  const [visibility, setVisibility] = useState<Record<string, boolean>>(
    Object.fromEntries(layers.map((l) => [l.id, l.visible]))
  );

  const toggle = (layerId: string) => {
    const next = !visibility[layerId];
    setVisibility((v) => ({ ...v, [layerId]: next }));
    if (map) {
      map.setLayoutProperty(layerId, "visibility", next ? "visible" : "none");
    }
  };

  return (
    <div className="absolute top-4 left-4 z-10 w-56 rounded-lg bg-white/95 shadow-lg backdrop-blur-sm">
      <div className="border-b border-gray-200 px-3 py-2">
        <h3 className="text-sm font-semibold text-gray-700">Layers</h3>
      </div>
      <ul className="max-h-60 overflow-y-auto p-2">
        {layers.map((layer) => (
          <li key={layer.id} className="flex items-center gap-2 rounded px-2 py-1.5 hover:bg-gray-50">
            <input
              type="checkbox"
              checked={visibility[layer.id] ?? true}
              onChange={() => toggle(layer.id)}
              className="h-3.5 w-3.5 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
            />
            <span className="flex-1 truncate text-xs text-gray-700">{layer.id}</span>
            <span className="text-[10px] text-gray-400">{layer.type}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
`,
      });
    }

    if (hasComponent("FeaturePopup")) {
      componentFiles.push({
        path: "src/components/FeaturePopup.tsx",
        content: `import { useEffect } from "react";
import maplibregl from "maplibre-gl";

interface Props {
  map: maplibregl.Map | null;
  spec: Record<string, unknown>;
}

export default function FeaturePopup({ map, spec }: Props) {
  useEffect(() => {
    if (!map) return;

    const layers = (spec.layers as Array<Record<string, unknown>>) ?? [];
    const clickableLayers = layers
      .filter((l) => ["circle", "fill", "line", "symbol"].includes(String(l.type)))
      .map((l) => String(l.id));

    const handlers: Array<{ layerId: string; handler: (e: maplibregl.MapMouseEvent) => void }> = [];

    for (const layerId of clickableLayers) {
      const handler = (e: maplibregl.MapMouseEvent) => {
        const features = map.queryRenderedFeatures(e.point, { layers: [layerId] });
        if (!features.length) return;
        const props = features[0].properties ?? {};
        const html = Object.entries(props)
          .map(([k, v]) => \`<div class="flex gap-2"><span class="font-medium text-gray-600">\${k}:</span><span class="text-gray-900">\${v}</span></div>\`)
          .join("");
        new maplibregl.Popup()
          .setLngLat(e.lngLat)
          .setHTML(\`<div class="space-y-1 text-xs p-1">\${html || "<em>No properties</em>"}</div>\`)
          .addTo(map);
      };
      map.on("click", layerId, handler);
      handlers.push({ layerId, handler });
      map.on("mouseenter", layerId, () => { map.getCanvas().style.cursor = "pointer"; });
      map.on("mouseleave", layerId, () => { map.getCanvas().style.cursor = ""; });
    }

    return () => {
      for (const { layerId, handler } of handlers) {
        map.off("click", layerId, handler);
      }
    };
  }, [map, spec]);

  return null;
}
`,
      });
    }

    if (hasComponent("Legend")) {
      componentFiles.push({
        path: "src/components/Legend.tsx",
        content: `import maplibregl from "maplibre-gl";

interface Props {
  map: maplibregl.Map | null;
  spec: Record<string, unknown>;
}

interface LegendEntry { id: string; type: string; color: string; }

function extractColor(paint: Record<string, unknown> | undefined, layerType: string): string {
  if (!paint) return "#6b7280";
  const key = layerType === "circle" ? "circle-color"
    : layerType === "fill" ? "fill-color"
    : layerType === "line" ? "line-color"
    : "text-color";
  const val = paint[key];
  return typeof val === "string" ? val : "#6b7280";
}

export default function Legend({ spec }: Props) {
  const layers = (spec.layers as Array<Record<string, unknown>>) ?? [];
  const entries: LegendEntry[] = layers.map((l) => ({
    id: String(l.id ?? "unknown"),
    type: String(l.type ?? "fill"),
    color: extractColor(l.paint as Record<string, unknown> | undefined, String(l.type)),
  }));

  return (
    <div className="absolute bottom-8 right-4 z-10 rounded-lg bg-white/95 shadow-lg backdrop-blur-sm">
      <div className="border-b border-gray-200 px-3 py-2">
        <h3 className="text-sm font-semibold text-gray-700">Legend</h3>
      </div>
      <ul className="space-y-1 p-2">
        {entries.map((entry) => (
          <li key={entry.id} className="flex items-center gap-2 px-1">
            <span className="h-3 w-3 rounded-sm flex-shrink-0" style={{ backgroundColor: entry.color }} />
            <span className="truncate text-xs text-gray-600">{entry.id}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
`,
      });
    }

    if (hasComponent("SearchBox")) {
      componentFiles.push({
        path: "src/components/SearchBox.tsx",
        content: `import { useState, useCallback } from "react";
import maplibregl from "maplibre-gl";

interface Props {
  map: maplibregl.Map | null;
  spec: Record<string, unknown>;
}

export default function SearchBox({ map, spec }: Props) {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<Array<{ id: string; label: string; lng: number; lat: number }>>([]);
  const [open, setOpen] = useState(false);

  const search = useCallback(() => {
    if (!map || !query.trim()) { setResults([]); return; }

    const layers = (spec.layers as Array<Record<string, unknown>>) ?? [];
    const found: Array<{ id: string; label: string; lng: number; lat: number }> = [];

    for (const layer of layers) {
      const sourceId = String(layer.source ?? "");
      const source = (spec.sources as Record<string, Record<string, unknown>>)?.[sourceId];
      if (!source || source.type !== "geojson") continue;
      const data = source.data as { features?: Array<Record<string, unknown>> } | undefined;
      if (!data?.features) continue;

      for (const feature of data.features) {
        const props = (feature.properties ?? {}) as Record<string, unknown>;
        const geom = feature.geometry as { type?: string; coordinates?: number[] } | undefined;
        if (!geom || geom.type !== "Point" || !geom.coordinates) continue;

        const text = Object.values(props).map(String).join(" ").toLowerCase();
        if (text.includes(query.toLowerCase())) {
          const name = String(props.name ?? props.title ?? props.label ?? Object.values(props)[0] ?? "Feature");
          found.push({ id: \`\${sourceId}-\${found.length}\`, label: name, lng: geom.coordinates[0], lat: geom.coordinates[1] });
        }
      }
    }

    setResults(found.slice(0, 10));
    setOpen(found.length > 0);
  }, [map, query, spec]);

  const flyTo = (lng: number, lat: number) => {
    if (map) map.flyTo({ center: [lng, lat], zoom: 14, duration: 1000 });
    setOpen(false);
  };

  return (
    <div className="absolute top-4 left-1/2 z-10 w-80 -translate-x-1/2">
      <div className="flex overflow-hidden rounded-lg bg-white shadow-lg">
        <input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && search()}
          placeholder="Search features..."
          className="flex-1 px-3 py-2 text-sm text-gray-700 outline-none placeholder:text-gray-400"
        />
        <button onClick={search} className="bg-blue-600 px-3 text-white hover:bg-blue-500">
          <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg>
        </button>
      </div>
      {open && (
        <ul className="mt-1 max-h-48 overflow-y-auto rounded-lg bg-white shadow-lg">
          {results.map((r) => (
            <li key={r.id}>
              <button onClick={() => flyTo(r.lng, r.lat)} className="w-full px-3 py-2 text-left text-xs text-gray-700 hover:bg-gray-50">
                {r.label} <span className="text-gray-400">({r.lng.toFixed(2)}, {r.lat.toFixed(2)})</span>
              </button>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
`,
      });
    }

    if (hasComponent("BasemapSwitcher")) {
      componentFiles.push({
        path: "src/components/BasemapSwitcher.tsx",
        content: `import { useState } from "react";
import maplibregl from "maplibre-gl";

const BASEMAPS = [
  { id: "osm", label: "Streets", style: "https://demotiles.maplibre.org/style.json" },
  { id: "dark", label: "Dark", style: "https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json" },
  { id: "light", label: "Light", style: "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json" },
];

interface Props {
  map: maplibregl.Map | null;
  spec: Record<string, unknown>;
}

export default function BasemapSwitcher({ map }: Props) {
  const [active, setActive] = useState("osm");

  const switchBasemap = (id: string) => {
    if (!map) return;
    const basemap = BASEMAPS.find((b) => b.id === id);
    if (!basemap) return;
    setActive(id);
    fetch(basemap.style)
      .then((r) => r.json())
      .then((style) => {
        const currentCenter = map.getCenter();
        const currentZoom = map.getZoom();
        map.setStyle(style);
        map.once("style.load", () => {
          map.setCenter(currentCenter);
          map.setZoom(currentZoom);
        });
      })
      .catch(() => {});
  };

  return (
    <div className="absolute top-4 right-4 z-10 flex gap-1 rounded-lg bg-white/95 p-1 shadow-lg backdrop-blur-sm">
      {BASEMAPS.map((b) => (
        <button
          key={b.id}
          onClick={() => switchBasemap(b.id)}
          className={\`rounded px-2.5 py-1 text-xs transition \${
            active === b.id ? "bg-blue-600 text-white" : "text-gray-600 hover:bg-gray-100"
          }\`}
        >
          {b.label}
        </button>
      ))}
    </div>
  );
}
`,
      });
    }

    return [
      {
        path: "package.json",
        content: JSON.stringify({
          name: ctx.projectName,
          version: "0.1.0",
          private: true,
          type: "module",
          scripts: {
            dev: "vite",
            build: "tsc -b && vite build",
            preview: "vite preview",
          },
          dependencies: {
            "@gis-engine/engine": "^0.2.0",
            "maplibre-gl": "^5.0.0",
            "react": "^18.3.0",
            "react-dom": "^18.3.0",
          },
          devDependencies: {
            "@types/react": "^18.3.0",
            "@types/react-dom": "^18.3.0",
            "@vitejs/plugin-react": "^4.3.0",
            "autoprefixer": "^10.4.0",
            "postcss": "^8.4.0",
            "tailwindcss": "^3.4.0",
            "typescript": "^5.7.0",
            "vite": "^5.4.0",
          },
        }, null, 2) + "\n",
      },
      {
        path: "vite.config.ts",
        content: `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
`,
      },
      {
        path: "tsconfig.json",
        content: JSON.stringify({
          compilerOptions: {
            target: "ES2022",
            lib: ["ES2022", "DOM", "DOM.Iterable"],
            module: "ESNext",
            moduleResolution: "bundler",
            jsx: "react-jsx",
            strict: true,
            esModuleInterop: true,
            skipLibCheck: true,
            outDir: "./dist",
          },
          include: ["src"],
        }, null, 2) + "\n",
      },
      {
        path: "tailwind.config.js",
        content: `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
`,
      },
      {
        path: "postcss.config.js",
        content: `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
      },
      {
        path: "index.html",
        content: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${cfg.title}</title>
</head>
<body class="m-0">
  <div id="root"></div>
  <script type="module" src="/src/main.tsx"></script>
</body>
</html>
`,
      },
      {
        path: "src/index.css",
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;

@import "maplibre-gl/dist/maplibre-gl.css";

html, body, #root {
  margin: 0;
  padding: 0;
  width: 100%;
  height: 100%;
}
`,
      },
      {
        path: "src/main.tsx",
        content: `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`,
      },
      {
        path: "src/App.tsx",
        content: `import { useEffect, useRef, useState } from "react";
import maplibregl from "maplibre-gl";
${componentImports}
import mapSpec from "../map.json";

export default function App() {
  const mapContainer = useRef<HTMLDivElement>(null);
  const [map, setMap] = useState<maplibregl.Map | null>(null);
  const spec = mapSpec as Record<string, unknown>;

  useEffect(() => {
    if (!mapContainer.current || map) return;

    const view = spec.view as { center?: [number, number]; zoom?: number } | undefined;
    const m = new maplibregl.Map({
      container: mapContainer.current,
      style: "https://demotiles.maplibre.org/style.json",
      center: view?.center ?? [0, 20],
      zoom: view?.zoom ?? 2,
    });

    m.addControl(new maplibregl.NavigationControl(), "bottom-right");

    const syncSpecToMap = (targetMap: maplibregl.Map) => {
      const sources = (spec.sources ?? {}) as Record<string, Record<string, unknown>>;
      for (const [id, src] of Object.entries(sources)) {
        if (!targetMap.getSource(id)) {
          targetMap.addSource(id, src as maplibregl.SourceSpecification);
        }
      }
      const layers = (spec.layers ?? []) as Array<Record<string, unknown>>;
      for (const layer of layers) {
        if (!targetMap.getLayer(String(layer.id))) {
          targetMap.addLayer(layer as maplibregl.LayerSpecification);
        }
      }
    };

    m.on("load", () => {
      syncSpecToMap(m);
      setMap(m);
    });
    m.on("style.load", () => {
      syncSpecToMap(m);
    });

    return () => { m.remove(); };
  }, []);

  return (
    <div className="relative h-screen w-screen">
      <div ref={mapContainer} className="h-full w-full" />
      {map && (
        <>
${componentRender}
        </>
      )}
    </div>
  );
}
`,
      },
      ...componentFiles,
      {
        path: "map.json",
        content: JSON.stringify({
          version: "0.2",
          sources: {
            points: {
              type: "geojson",
              data: { type: "FeatureCollection", features: [] },
            },
          },
          layers: [
            {
              id: "points-layer",
              type: "circle",
              source: "points",
              paint: { "circle-radius": 6, "circle-color": "#3b82f6" },
            },
          ],
        }, null, 2) + "\n",
      },
      {
        path: "README.md",
        content: `# ${ctx.projectName}

Generated by \`create-gis-map\` v${ctx.cliVersion} using the **app** template.

## App Type

**${cfg.appType}** — ${cfg.description}

Components: ${cfg.components.join(", ")}

## Usage

\`\`\`bash
npm install
npm run dev
\`\`\`

## Provider

Current provider: \`${ctx.provider}\`

## AI Generation

Re-generate with a new prompt:

\`\`\`bash
npx create-gis-map . --generate --template app --prompt "Your description here" -y
\`\`\`
`,
      },
    ];
  },
};

const registry: Record<TemplateName, Template> = {
  "static-html": staticHtmlTemplate,
  "vite-ts": viteTsTemplate,
  "mapspec": mapspecTemplate,
  "app": appTemplate,
};

export function getTemplate(name: string): Template | undefined {
  return registry[name as TemplateName];
}
