import { existsSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

function readText(path: string): string {
  return readFileSync(resolve(repoRoot, path), "utf8");
}

describe("public docs consistency", () => {
  it("keeps v1.0.0 entry points aligned", () => {
    const files = [
      "README.md",
      "CHANGELOG.md",
      "docs/website/release-notes.md",
      "docs/migration/v0.x-to-v1.0.md",
    ];

    for (const file of files) {
      expect(readText(file), `${file} should mention v1.0.0`).toContain("v1.0.0");
    }
  });

  it("links migration index to the main v1.0 guide", () => {
    expect(readText("docs/migration/README.md")).toContain("./v0.x-to-v1.0.md");
  });

  it("keeps generated API reference entry points visible", () => {
    expect(readText("docs/website/api/index.md")).toContain("/api/reference/engine/");
    expect(readText("docs/website/api/index.md")).toContain("/api/reference/ai/");
    expect(readText("docs/website/api/index.md")).toContain("/api/reference/cli/");
    expect(readText("docs/website/api/engine.md")).toContain("/api/reference/engine/");
    expect(readText("docs/website/api/ai.md")).toContain("/api/reference/ai/");
    expect(readText("docs/website/api/cli.md")).toContain("/api/reference/cli/");
    expect(readText("docs/website/api/reference/engine/index.md")).toContain("generated by `pnpm docs:api`");
  });

  it("keeps the three core example readmes in the standard structure", () => {
    const exampleFiles = [
      "examples/getting-started/README.md",
      "examples/basic-geojson/README.md",
      "examples/pmtiles-local/README.md",
    ];

    for (const file of exampleFiles) {
      const text = readText(file);
      expect(text, `${file} should have Goal section`).toContain("## Goal");
      expect(text, `${file} should have Prerequisites section`).toContain("## Prerequisites");
      expect(text, `${file} should have Run section`).toContain("## Run");
      expect(text, `${file} should have Expected Output section`).toContain("## Expected Output");
      expect(text, `${file} should have Limits And Follow-up section`).toContain("## Limits And Follow-up");
    }
  });

  it("checks generated API reference directories into the docs tree", () => {
    expect(existsSync(resolve(repoRoot, "docs/website/api/reference/engine/index.md"))).toBe(true);
    expect(existsSync(resolve(repoRoot, "docs/website/api/reference/ai/index.md"))).toBe(true);
    expect(existsSync(resolve(repoRoot, "docs/website/api/reference/cli/index.md"))).toBe(true);
  });
});
